[tool.poetry]
name = "nbody-sim"
version = "0.1.0"
description = "Reusable N-body gravitational simulation engine"
authors = ["Pedro Macedo Flores <pedro.macedo17@proton.me>"]
readme = "README.md"
packages = [{ include = "nbody_sim" }]

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
numpy = "^2.4.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
